### ISSUE TITLE
`onchange` is no longer called unless you return a new object from `onaction`

### ISSUE THREAD

**Issue by colingourlay** [sethvincent/send-action#6]
If you're being 'pure' and using `Object.assign` or an immutable library, this isn't an issue, but if you're just changing the value of one of the properties, the new `2.0.0` shallow object comparison succeds and nothing happens.

If this is intentional, that's cool, but the docs lead me to believe the `onaction` handler is modifying the `state` argument and returning it, which fails.

**Comment by sethvincent** [comment]
Thanks that's definitely awkward behavior. I'll update the docs to make it clear that creating a new object is the preferred approach. I'll leave this open for now though in case we want to revisit it and change the behavior.

**Comment by colingourlay** [comment]
To be fair, it's an acceptable breaking change for a major release. It only caught me out because 1.x let me write code the way I did, and it broke on upgrade.

**Comment by sethvincent** [comment]
I've modified this behavior for v3.0.0.

In the latest version the `onChange` function is called if an object is returned from `onAction`.

When an object is returned from `onAction` it extends the internal state object.

The `state` argument of the `onAction` function is a copy of the internal state.

So it sounds like the style you used previously would now work again with v3. 🙃
